import AlumniCard from "@/components/cards/alumniCard";
import ExecutiveCard from "@/components/cards/executiveCard";
import PageCover from "@/components/pageCover";
import Head from "next/head";

export default function ExecutiveMembersPage() {
  return (
    <>
      <Head>
        <title>PSTU CSE CLUB - An non-profit organization</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="alumnies__page">
          <PageCover
            title="Our Guidence"
            subTitle="Driving force for our comminuty"
          />
          <div className="alumnies__wrapper">
            <AlumniCard />
            <AlumniCard />
            <AlumniCard />
            <AlumniCard />
            <AlumniCard />
            <AlumniCard />
            <AlumniCard />
            <AlumniCard />
            <AlumniCard />
            <AlumniCard />
            <AlumniCard />
            <AlumniCard />
          </div>
        </div>
      </div>
    </>
  );
}
