import React from "react";
import Schedule from "@/components/schedule";
import Head from "next/head";
import Image from "next/image";
import { useMediaQuery } from "react-responsive";
import parse from "html-react-parser";

export default function EventPreviewPage({ event }) {
  const isTabletOrMobile = useMediaQuery({ query: "(max-width: 600px)" });
  console.log(event);
  return (
    <>
      <Head>
        <title>{event.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="event-preview-page" className="event">
        <div className="event__coverimg__wrapper">
          {" "}
          {!isTabletOrMobile && (
            <Image
              className="event__coverimg"
              src={event.coverImgLand}
              alt="event cover image"
              fill
            />
          )}
          {isTabletOrMobile && (
            <Image
              className="event__coverimg"
              src={event.coverImgPort}
              alt="event cover image"
              fill
            />
          )}
        </div>

        <main className="event__contents">
          {event?.sponsors.length > 0 && (
            <div className="event__sponsors">
              <h3 className="event__sponsors__title">Sponsors</h3>
              <div className="event__sponsors__wrapper">
                {event?.sponsors.map((s, i) => {
                  return (
                    <div key={i} className="event__sponsor">
                      <div className="event__sponsor__img__wrapper">
                        <Image
                          className="event__sponsor__img"
                          src={URL.createObjectURL(s.img)}
                          alt={s.name}
                          fill
                        />
                      </div>
                      <h6 className="event__sponsor__name">{s.name}</h6>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          <article className="event__article">
            {parse(event.description)}
          </article>
          {event?.childs?.length > 0 && (
            <div className="event__events">
              <h3 className="event__events__title">
                {event.title + " Events"}
              </h3>
              <div className="event__events__wrapper">
                {event?.childs?.map((e, i) => {
                  return (
                    <div key={i} className="event__event">
                      <div className="event__event__img__wrapper">
                        <Image
                          className="event__event__img"
                          fill
                          alt={e.title + "-img"}
                          src={e.img}
                        />
                      </div>
                      <div className="event__event__texts">
                        <h3 className="event__event__title">{e.title}</h3>
                        <p className="event__event__para">
                          {e.shortDescription}
                        </p>
                        <button className="event__event__btn">View</button>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
          {event?.schedules.length > 0 && (
            <div className="event__schedule__wrapper">
              <Schedule schedules={event.schedules} />
            </div>
          )}
        </main>
      </div>
    </>
  );
}
