import ExecutiveCard from "@/components/cards/executiveCard";
import Editor from "@/components/editor";
import EventDetailsForm from "@/components/event/eventDetailsForm";
import EventImagesForm from "@/components/event/eventImagesForm";
import ImagesForm from "@/components/event/eventImagesForm";
import PageCover from "@/components/pageCover";
import Stepper from "@/components/stepper";
import Head from "next/head";
import { useState } from "react";

const steps = [
  { value: "Provide Details" },
  {
    value: "Provide Contents",
  },
  { value: "Provide Images" },
  { value: "Preview" },
];

function chooseComp(step) {
  if (step === 1) return <EventDetailsForm />;
  if (step === 2) return <Editor />;
  if (step === 3) return <EventImagesForm />;
  if (step === 4) return <h1>Preview</h1>;
}
export default function AddEvent() {
  const [currentStep, setCurrentStep] = useState(1);

  return (
    <>
      <Head>
        <title>PSTU CSE CLUB - An non-profit organization</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="addevent__page">
          <div className="addevent__wrapper">
            <Stepper step={currentStep} steps={steps} />
            <div className="addevent__step__details">
              {chooseComp(currentStep)}
              <div className="addevent__step__btns">
                {currentStep !== 1 && (
                  <button
                    onClick={() => {
                      setCurrentStep(currentStep - 1);
                    }}
                    className="addevent__step__btn addevent__step__btn--left"
                  >
                    Prev
                  </button>
                )}
                {currentStep !== steps.length && (
                  <button
                    onClick={() => {
                      setCurrentStep(currentStep + 1);
                    }}
                    className="addevent__step__btn addevent__step__btn--right"
                  >
                    Next
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
