import BlogCard from "@/components/cards/blogCard";
import PageCover from "@/components/pageCover";
import Head from "next/head";
import Image from "next/image";
import React from "react";

export default function Blog() {
  return (
    <>
      <Head>
        <title>PSTU CSE CLUB - An non-profit organization</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="blog__page">
        <PageCover />
        <div className="blog__page__wrapper">
          {/* <main className="blog__page__blogs"></main> */}

          {/* <div
            style={{
              marginTop: "5rem",
              display: "flex",
              gap: 20,
              flexWrap: "wrap",
            }}
          > */}
          <BlogCard />
          <BlogCard />
          <BlogCard />
          <BlogCard />
          <BlogCard />
          <BlogCard />
          <BlogCard />
          <BlogCard />
          <BlogCard />
          <BlogCard />
          {/* </div> */}
        </div>
      </div>
    </>
  );
}
