import { CssVarsProvider, GlobalStyles } from "@/app/lib/mui";
import "../globals.css";
import { Inter } from "next/font/google";
import customTheme from "./theme";
import Head from "next/head";
import Header from "./components/header";
import Footer from "./components/footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function UserLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <CssVarsProvider disableTransitionOnChange theme={customTheme}>
          <GlobalStyles
            styles={{
              "[data-feather], .feather": {
                color: "var(--Icon-color)",
                margin: "var(--Icon-margin)",
                fontSize: "var(--Icon-fontSize, 20px)",
                width: "1em",
                height: "1em",
              },
            }}
          /> */}
        <Header />
        {children}
        <Footer />
        {/* </CssVarsProvider> */}
      </body>
    </html>
  );
}
export const metadata = {
  title: "CSE CLUB, PSTU - Welcome to the cse club",
  description:
    "CSE CLUB, PSTU is the largest computer science club in the Barisal Division. Its works to provide support and resources to the computer science student of pstu",
};
